### ISSUE TITLE
JS -> TS

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-regex#18]
Convert our main files from JS to TS to make them safer and more readable.

**Comment by SneakY-NickY** [comment]
I'm having issues installing dependencies for this project. For some odd reason, it's trying to look for a module inside:

> C:\Users\Martin\Desktop\zk-regex\node_modules\node_modules\cargo-cp-artifact\bin\cargo-cp-artifact.js

When the correct path should be:

> C:\Users\Martin\Desktop\zk-regex\node_modules\cargo-cp-artifact\bin\cargo-cp-artifact.js

![image](https://github.com/zkemail/zk-regex/assets/92948020/2a404157-e70f-490e-9daa-dddd27f0c87f)

Any way I could possibly fix this myself?

**Comment by SneakY-NickY** [comment]
I've tried using `npm/npm run` as a replacement for `yarn` and everything seems to work. Still a bit weird since both should be doing the same thing afaik.

**Comment by Divide-By-0** [comment]
@SneakY-NickY we've pushed some updates. let us know if the new build works!

**Comment by SneakY-NickY** [comment]
That's great to hear! I'll try it out tomorrow and show you the WIP as well.

**Comment by SneakY-NickY** [comment]
> @SneakY-NickY we've pushed some updates. let us know if the new build works! can we see your WIP PR?

I've tried out the new build and unfortunately got the same errors 😢 

Here's the WIP PR 😄 : https://github.com/zkemail/zk-regex/pull/29
