### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/zk-regex#35]
For the regex generation flow, add a few sample regexes or regex configs, then generate a final circom file and use circom-tester to ensure that it in fact correctly matches that regex and reveals the right group. This will be needed to merge in #31.

**Comment by SoraSuegami** [comment]
The generated circuits are already tested here.
https://github.com/zkemail/zk-regex/tree/main/packages/circom/tests
Those tests automatically generate the circom circuits for the regexes in [the circom package](https://github.com/zkemail/zk-regex/tree/main/packages/circom) and check the revealed substrings.
